### ISSUE TITLE
Error : fails to download (Windows 7)

### ISSUE THREAD

**Issue by marcrw** [Deathspike/crunchyroll.js#10]
I am getting the following error on Windows 7.

    C:\Users\Ty>crunchyroll http://www.crunchyroll.com/himouto-umaru-chan
    Fetching Himouto! Umaru-chan 01x01 [CrunchyRoll]
    Error: Command failed: C:\Windows\system32\cmd.exe /s /c ""C:\Users\Ty\AppData\R
    oaming\npm\node_modules\crunchyroll\bin\rtmpdump.exe" -r "undefined" -y "undefin
    ed" -W "http://www.crunchyroll.com/swf/StandardVideoPlayer.swf" -o "C:\Users\Ty\
    Himouto! Umaru-chan\Himouto! Umaru-chan 01x01 [CrunchyRoll]""
    RTMPDump v2.4
    (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
    ERROR: RTMP URL: No :// in url!
    WARNING: Couldn't parse the specified url (undefined)!
    ERROR: You must specify a hostname (--host) or url (-r "rtmp://host[:port]/playp
    ath") containing a hostname

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

**Comment by RainerZA** [comment]
I get a similar issue on OSX

**Comment by SajeOne** [comment]
Same issue here on Arch.

**Comment by crunchyrolI** [comment]
I got that issue when I tried to download episode 467 of Naruto Shippuden, I typed 467, but it started to download 468 (which hasn't come out yet). I then typed 466 and it downloaded 467 successfully.
