### ISSUE TITLE
Fetching/download error...

### ISSUE THREAD

**Issue by reynold-lariza** [Deathspike/crunchyroll.js#12]
Fetching The Asterisk War 01x01 [CrunchyRoll]

Error: Command failed: /bin/sh -c rtmpdump -r "rtmpe://c19fs.fplive.net/c19?nvb=20151103140849&nva=20151103180949&token=06b8b026b59db40d85e79" -y "mp4:s/ve1989861/video.mp4" -W "http://www.crunchyroll.com/swf/StandardVideoPlayer.swf" -o "/crunchyroll/The Asterisk War/The Asterisk War 01x01 [CrunchyRoll].mp4"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 9
INFO: Connected...
ERROR: rtmp server sent error
ERROR: rtmp server requested close

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

**Comment by sinnx3** [comment]
I'm sure this has something to do with it since the other Crunchyroll downloader "Crunchyroll Downloader Toolkit DX" (Python) Stopped printing out titles etc.. due to their player .swf name revision.

http://i.imgur.com/3gnmfVe.png
