### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by Jfigs101** [Deathspike/crunchyroll.js#23]
has anyone encountered the issue below? This outputs immediately after sending the command. 

Error: socket hang up
    at SecurePair.error (tls.js:1013:23)
    at EncryptedStream.CryptoStream._done (tls.js:705:22)
    at CleartextStream.read [as _read] (tls.js:496:24)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:301:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:356:12)
    at endWritable (_stream_writable.js:363:3)
    at EncryptedStream.Writable.end (_stream_writable.js:341:5)

**Comment by Jfigs101** [comment]
After further testing, it appeared that the episode I was attempting to download may have been causing the error. I decided to skip over that particular episode using the '-e' and have not had a problem since.
