### ISSUE TITLE
for certain episodes get ERROR: RTMP URL: No :// in url!

### ISSUE THREAD

**Issue by xapples** [Deathspike/crunchyroll.js#24]
Works fine for certain episodes. Then I get this wall of text (I've replaced the show name with 'show' and my username with 'user':

Fetching [show] 01x80 [CrunchyRoll]
Error: Command failed: rtmpdump -r "" -y "http://serve.cxcdn.net/s/v/teil8g5mtlz2p2d/m/9f1f69aef7a8e16aafd9332f77f1d86f/jaJP.m3u8?v=af9cc7be419eaa94035efd9f5c986404&k=UUM1bEtxSFFXeGJuWC80OUVzRXh1RnFFbE5JPV97ImEiOiI5MSw2LGphSlAsIiwiYyI6MTQ2MTM2ODQ5MiwiZCI6ImNyYW5pbWUiLCJnIjoiWloiLCJoIjoidGVpbDhnNW10bHoycDJkIiwibCI6NzIwMCwicCI6IjEiLCJyIjoiYzMwZDgyIiwicyI6OTc2ODk3LCJ0IjoxNDcxMDAzNzkwLCJ2IjozfQ" -W "http://www.crunchyroll.com/swf/StandardVideoPlayer.swf" -o "/Users/[user]/[show]/[show] 01x80 [CrunchyRoll].m3u8?v=af9cc7be419eaa94035efd9f5c986404&k=UUM1bEtxSFFXeGJuWC80OUVzRXh1RnFFbE5JPV97ImEiOiI5MSw2LGphSlAsIiwiYyI6MTQ2MTM2ODQ5MiwiZCI6ImNyYW5pbWUiLCJnIjoiWloiLCJoIjoidGVpbDhnNW10bHoycDJkIiwibCI6NzIwMCwicCI6IjEiLCJyIjoiYzMwZDgyIiwicyI6OTc2ODk3LCJ0IjoxNDcxMDAzNzkwLCJ2IjozfQ"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
ERROR: RTMP URL: No :// in url!
WARNING: Couldn't parse the specified url ()!
ERROR: You must specify a hostname (--host) or url (-r "rtmp://host[:port]/playpath") containing a hostname

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

Any ideas how to work around this? Thanks in advance!

**Comment by Godzil** [comment]
I don't know why, but it seems that the call src/episodes.ts in scrapePlayer the return from the call at "/xml/?req..." return an object with player['default:preload'].stream_info.host to be empty.

It's possible they've made a slight change to that call that in some condition the host is empty

**Comment by Jfigs101** [comment]
Also having this issue. Would like to get a fix if possible.

**Comment by Godzil** [comment]
I may have a potential solution, I'm testing it right now.

**Comment by Godzil** [comment]
It's pushed on my fork, I'm testing it currently, if it works for one episode I will make a pull request. I can't test the fix under windows/linux so it may fail.

**Comment by Jfigs101** [comment]
Thanks for the work on this. I will test on Linux and report back.

**Comment by Jfigs101** [comment]
How/where is the  variable "mode" defined in stream?

**Comment by Jfigs101** [comment]
/usr/local/lib/node_modules/crunchyroll/dist/video/stream.js:9
if (mode == "RTMP")
    ^
ReferenceError: mode is not defined
    at Object.default_1 [as stream] (/usr/local/lib/node_modules/crunchyroll/dist/video/stream.js:9:5)
    at downloadVideo (/usr/local/lib/node_modules/crunchyroll/dist/episode.js:89:21)
    at /usr/local/lib/node_modules/crunchyroll/dist/episode.js:51:13
    at Object.oncomplete (fs.js:107:15)

**Comment by Godzil** [comment]
Oups, forgot to add that argument, just a minute I update that

**Comment by xapples** [comment]
Thanks for all your hard work! I'm sorry to be totally inept and new to all this -- would you mind telling me how I can use these changes? Is there something I can download, or some files I can change?

**Comment by Jfigs101** [comment]
@xapples I think the easiest way for you to do this is to first download Godzil's version. Then unzip it if need be. Find deathspikes version on your machine. Find out where node packages are installed. Drag and drop Godzil's changed files with the .js extension into your original destination. Let me know if that works.

**Comment by Godzil** [comment]
I'm not really into node/js things, but I think you can do something like

npm install -g godzil/crunchyroll

**Comment by Godzil** [comment]
I should update my branch btw I've made a lot of changes, especially corrections on how to handle series names, and samll things like this. I'm still looking at a good way to correct some metadata bugs in CR where some season have the same number (RWBY is an example, Season 2 is not tagged as season 2, and Fate/Kaleid Liner Prisma Illya have two "Season 3"...)

**Comment by Jfigs101** [comment]
Definitely. I would like to adapt those changes.

**Comment by Godzil** [comment]
I will but not right now as I have to clean things a lot (if I had time I would rewrite most of the original project there are a lot of incoherent things done, but I don"t have that time..)
I've also changed it to ignore non released episodes (you now the "coming soon" one)

**Comment by xapples** [comment]
(Sorry to derail again)
Thanks both. Godzil: sadly npm install -g godzil/crunchyroll.js gives me a lot of errors (I can list them if you want? mainly things like 'npm ERR! Command failed: git clone --template=/Users/[user]/.npm/_git-remotes/_templates --mirror git@github.com:godzil/crunchyroll.git /Users/[user]/.npm/_git-remotes/git-github-com-godzil-crunchyroll-git-168294a9'). 

Also Jfigs101, when I look into the node modules of the deathspike version, instead of having files like 'episode.ts', I have 'episode.d.ts', 'episode.js' and 'episode.js.map', none of which seem to have similar code to Godzil's files; replacing say 'episode.js' with Godzil's 'episode.ts', even if renamed to a .js file, does not work. Is there anything else you would suggest (or anything I'm doing wrong)? 

Thanks once again!

**Comment by Godzil** [comment]
Try without the -g option, you may need root rights to use the global option.

I've got some warn when trying here but they are nothing serious about:

`$ npm install godzil/crunchyroll.js
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
[...]
npm WARN enoent ENOENT: no such file or directory, open '/Users/godzil/package.json'
npm WARN godzil No description
npm WARN godzil No repository field.
npm WARN godzil No README data
npm WARN godzil No license field.`

**Comment by xapples** [comment]
Thanks -- it installs fine! How then do I run it? just use the 'crunchyroll' command, or something else?

**Comment by Godzil** [comment]
It's worth trying!

I honestly don't know where npm install the thing, it *may* have created something in /use/local/bin or maybin in $HOME/bin

if you are under unix (Linux/OS X) of course, for Windows, I have no idea

**Comment by Jfigs101** [comment]
The .ts and .js is the way the compilation of the files works. If I'm not mistaken .js compiles to .ts. Just replace the .js files with each other. Don't worry about the others.

**Comment by Jfigs101** [comment]
Godzil, whenever you get a chance. Those changes do interest me as the original has had no activity on it and lacked some metadata compatibility.

**Comment by xapples** [comment]
Godzil, your install appears to just contain the 'bin' folder, not the 'dist' or 'node_modules' from the original?

Jfigs101, it doesn't seem to work with just the .ts files replacing the equivalent .js files (& renaming them) -- it comes up with the error 'Error: Cannot find module '/usr/local/lib/node_modules/crunchyroll/dist/cli'

**Comment by Jfigs101** [comment]
Do not worry about the .ts files. Copy over, for example, episodes.js from Godzil's to overwrite episode.js from deathspikes. Sorry for the confusion?

**Comment by xapples** [comment]
ah -- there the issue is that Godzil's apparently doesn't have any .js files at the moment! In the original crunchyroll install, they are in the dist folder, but Godzil's crunchyroll install is lacking that folder and the node_modules folder, containing only the bin folder. Am I missing something obvious?

**Comment by Godzil** [comment]
when you install using npm, the *.ts files are converted to *.js file, they are not directly compatible, and that's why you don't see the exact same thing between the github depot and what is on your drive

**Comment by xapples** [comment]
Sure, thanks. The issue is there are no .js or .ts files at all in the npm install, unlike the original npm install.

**Comment by xapples** [comment]
Okay, I've downloaded the original code and tried to install directly. The idea would be that I could replace the ts files in the original with Godzil's ts files, and install from that. However, I get the following error, even with the original code:

Failed at the crunchyroll@1.1.5 tsd script 'tsd reinstall -o -s'.
Failed at the crunchyroll@1.1.5 prepublish script 'npm run tsd && tsc'.

Any ideas? Thanks once again, sorry for the annoyance.

**Comment by xapples** [comment]
Okay, I sorted it out by running those two commands separately and then removing those lines from the package.json file, and everything worked -- it installed, woop woop!

However, Godzil, unfortunately when I try to download an episode, the following happens (e.g.):
Fetching Naruto Shippuden 01x80 [CrunchyRoll]
...and then nothing happens, the script stops with no errors, and nothing is downloaded. It just returns to $. Thoughts? This now seems like a problem with your code, rather than my install (sorry for derailing the thread so much with my own personal ineptitude).

**Comment by Godzil** [comment]
I've published my changes as "crunchy" on npm so please try to remove the current isntallation of crunchyroll, then install my fork by using

npm install -g crunchy

I can't test it right now, but it build correctly, there were a silly mistake in the version on github that I've corrected..

**Comment by xapples** [comment]
Perfect, thank you so much! Really appreciate all your help :D

**Comment by Jfigs101** [comment]
Godzil, is it necessary to remove "crunchyroll' to test your version out?

**Comment by Godzil** [comment]
nope as there is no longuer a clash between executable names

**Comment by lbickmore** [comment]
Any update the root issue of `ERROR: RTMP URL: No :// in url!` ?

**Comment by jakepbrown27** [comment]
just have two questions @Godzil 1) Is there a "production" branch to pull down or is -crunchy still the way to go? (was having the // url issue with "crunchyroll) and 2) you've save me so much time with this; how do I donate?

**Comment by Godzil** [comment]
Hi, I'm not the developer of the original tool, but I fear that it's no longuer maintained and my fork should be considered as the main thing now I fear.

As for donation if you really want to you can go to my blog at http://www.986-studio.com you will find more here in the left side bar.

**Comment by leroygumede** [comment]
If there was more documentation on the dev side I would love to help. @Godzil Its best if you request a Transfer of ownership. There is a number of us who really want to use this.

**Comment by Godzil** [comment]
I don't think a "transfer" is needed, just stop using "crunchyroll.js" and use Godzil/Crunchy which is my fork.

I'm not here to "steal" @Deathspike work, if he want to resume working on this project I will be happy if he integrate my changes. And I've changes my fork to use a different name so that they can coexist in the npm repository.
Crunchy is currently up to date and compatible with recent version of Crunchyroll website, I haven't had a lot of time to implement my planned version 2 in the last week, but work on that will resume shortly (when I get back a broadband connection) but if there is any big changes that need to update urgently I try to update it as soon as possible (and I've already done that a number of time since I've started my fork).

I don't plan to takeover Crunchyroll.js or use this name. Crunchy is now somewhat independent until work resume here, unless my version differ too much. (which will happen once Crunchy is in version 2, but it's going to take some time as it will need large changes in the current code base)

**Comment by Godzil** [comment]
If you really no longer want to work on your app, I'm ok to maintain crunchyroll.js to keep it working. That does not mean I will stop working on Crunchy, my local changes (which are not on the depot) differ too much from the original branch and is a bit too experimental for now.
