### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Deathspike/crunchyroll.js#31]
This is the error I receive when using the command 

crunchyroll http://www.crunchyroll.com/fairy-tail

Have used the -u and -p flags to add the account already, not sure where to go from here

Fetching Fairy Tail 01x01 [CrunchyRoll]
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.extname (path.js:889:5)
    at downloadVideo (C:\Users\username\AppData\Roaming\npm\node_modules\crunchyroll\dist\episode.js:89:92)
    at C:\Users\username\AppData\Roaming\npm\node_modules\crunchyroll\dist\episode.js:51:13
    at downloadSubtitle (C:\Users\username\AppData\Roaming\npm\node_modules\crunchyroll\dist\episode.js:72:16)
    at C:\Users\username\AppData\Roaming\npm\node_modules\crunchyroll\dist\episode.js:46:9
    at C:\Users\username\AppData\Roaming\npm\node_modules\crunchyroll\node_modules\mkdirp\index.js:47:26
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by xXxBobDolexXx** [comment]
After testing in a virtual machine, I am also getting this error using the same command:
crunchyroll http://www.crunchyroll.com/fairy-tail

Fetching Fairy Tail 01x01 [CrunchyRoll]
Error: Command failed: C:\Windows\system32\cmd.exe /s /c ""C:\Users\username\AppData\Roaming\npm\node_modules\crunchyroll\bin\rtmpdump.exe" -r "undefined" -y "undefined" -W "http://www.crunchyroll.com/swf/StandardVideoPlayer.swf" -o "C:\Users\username\Fairy Tail\Fairy Tail 01x01 [CrunchyRoll]""
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
ERROR: RTMP URL: No :// in url!
WARNING: Couldn't parse the specified url (undefined)!
ERROR: You must specify a hostname (--host) or url (-r "rtmp://host[:port]/playpath") containing a hostname

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by xXxBobDolexXx** [comment]
Will close this, Godzils fork works great, will link in case anyone sees this issue

https://github.com/Godzil/crunchyroll.js
