### ISSUE TITLE
Persona 4 Golden fails to download unless SRT subs manually chosen

### ISSUE THREAD

**Issue by stordoff** [Deathspike/crunchyroll.js#6]
Other anime (and now drama, thanks!) download fine, but Persona 4 The Golden Animation fails with the following error:

    E:\CR\p4g>crunchyroll http://www.crunchyroll.com/persona4-the-golden-animation
    TypeError: undefined is not a function
    at style (C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\dist\subtitle\formats\ass.js:39:72)
    at C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\dist\subtitle\formats\ass.js:14:45
    at Parser.<anonymous> (C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\node_modules\xml2js\lib\xml2js.js:425:18)
    at Parser.emit (events.js:107:17)
    at Object.onclosetag (C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\node_modules\xml2js\lib\xml2js.js:394:26)
    at emit (C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\node_modules\xml2js\node_modules\sax\lib\sax.js:615:33)
    at emitNode (C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\node_modules\xml2js\node_modules\sax\lib\sax.js:620:3)
    at closeTag (C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\node_modules\xml2js\node_modules\sax\lib\sax.js:861:5)
    at Object.write (C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\node_modules\xml2js\node_modules\sax\lib\sax.js:1294:29)
    at Parser.exports.Parser.Parser.parseString (C:\Users\[User]\AppData\Roaming\npm\node_modules\crunchyroll\node_modules\xml2js\lib\xml2js.js:444:31)

Selecting SRT as the subtitle format appears to work (currently downloading to test):

    E:\CR\p4g>crunchyroll -f srt http://www.crunchyroll.com/persona4-the-golden-animation
    Fetching Persona4 the Golden ANIMATION 01x01 [CrunchyRoll]

**Comment by Deathspike** [comment]
Thanks! This was an issue that appeared when a subtitle did not have multiple styles. Most subtitles have more than one style to differentiate between spoken text, signs, karaoke, and so forth. Apparently CR doesn't encode multiple styles an array, so we know explicitly make an array if it's not one yet. Released in 1.1.3.
