### ISSUE TITLE
Fails to pull on Ubuntu 12.04 and 14.04

### ISSUE THREAD

**Issue by majorcyto** [Deathspike/crunchyroll.js#9]
Hi, i followed the guide for Ubuntu and have a 12.04 server and a 14.04 server... Both however gave the same error which is this..

TypeError: Object 88171483 has no method 'toJSNumber'
    at magic (/usr/lib/node_modules/crunchyroll/dist/subtitle/decode.js:53:45)
    at key (/usr/lib/node_modules/crunchyroll/dist/subtitle/decode.js:42:39)
    at decrypt (/usr/lib/node_modules/crunchyroll/dist/subtitle/decode.js:23:59)
    at Object.main [as decode] (/usr/lib/node_modules/crunchyroll/dist/subtitle/decode.js:11:20)
    at downloadSubtitle (/usr/lib/node_modules/crunchyroll/dist/episode.js:72:14)
    at /usr/lib/node_modules/crunchyroll/dist/episode.js:45:9
    at /usr/lib/node_modules/crunchyroll/node_modules/mkdirp/index.js:30:20
    at Object.oncomplete (fs.js:108:15)

I also tried using the direct repo and use the latest version of nodejs and npm however i still got the same error. I am using my login credentials to login to Crunchy Roll. What can i do?

**Comment by majorcyto** [comment]
I also tried doing it with a direct episode link...

```
http://www.crunchyroll.com/akame-ga-kill/episode-1-kill-the-darkness-656895
```

And that time it did not give me an error, but it also did.. nothing. No video file or anything in the folder.

**Comment by majorcyto** [comment]
I did see that my version of nodejs and npm were not correct, so i removed them and re-installed them from the latest repo and now have...

```
root@dev2:~/test2# nodejs -v
v0.12.4
root@dev2:~/test2# npm -v
2.10.1
root@dev2:~/test2#
```

However, i am still getting...

```
TypeError: undefined is not a function
    at magic (/usr/local/lib/node_modules/crunchyroll/dist/subtitle/decode.js:53:45)
    at key (/usr/local/lib/node_modules/crunchyroll/dist/subtitle/decode.js:42:39)
    at decrypt (/usr/local/lib/node_modules/crunchyroll/dist/subtitle/decode.js:23:59)
    at Object.main [as decode] (/usr/local/lib/node_modules/crunchyroll/dist/subtitle/decode.js:11:20)
    at downloadSubtitle (/usr/local/lib/node_modules/crunchyroll/dist/episode.js:72:14)
    at /usr/local/lib/node_modules/crunchyroll/dist/episode.js:45:9
    at /usr/local/lib/node_modules/crunchyroll/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:95:15)
```

I've done as much debugging and searching as i can i think im at a loss here lol.

**Comment by majorcyto** [comment]
Sorry for all the comments, i also just tried it on Debian 8 and it also failed with the same error so now i truly have exhausted all my options. =P

**Comment by Deathspike** [comment]
Thanks for the detailed experimentation and report :+1: 

I traced the problem back to a change in `big-integer`, one of the dependencies that this application uses, and it appears that a minor version bump removed a function (the `toJSNumber` function). I locked down the dependencies to the old version by *NOT* allowing minor versions to be used, so you should now get `crunchyroll.js` in the exact state I test in. That is..

    npm install -g crunchyroll
    crunchyroll --version

You should be at `1.1.5` and have no further issues. Otherwise, run `npm -g outdated --depth 1` and check if `big-integer` under `crunchyroll.js` has the correct version, which should be `1.4.4`. If not, `npm uninstall -g crunchyroll` and `npm install -g crunchyroll` to reinstall from scratch.

Let me know! :-)

**Comment by majorcyto** [comment]
Hi, thanks so much.. that did resolve that error! However now i am getting this one. =[

```
Fetching Akame ga Kill! 01x01 [CrunchyRoll]
Error: Command failed: RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 9
INFO: Connected...
ERROR: rtmp server sent error
ERROR: rtmp server requested close

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

I tried on multiple OS's again, i thought maybe my librtmp was out dated potentially.. so i added librtmp1, 0, and dev hoping it would help lol. But im not sure now..

**Comment by Deathspike** [comment]
That's weird. Ubuntu has had `rtmpdump` 2.4 in their repositories forever now. And the command is obviously showing that you are using the latest version of it. I'll have to test this on an actual Linux VM. I'll begin setting one up as it appears I lost my last Ubuntu VM. To be continued. :)

**Comment by majorcyto** [comment]
Hi, i also just tried it on my Windows Desktop computer just to see (I don't want to use it on Windows, i want to use it through my server, but i thought i better test it) and i actually got the same exact error on windows 8.1..

**Comment by majorcyto** [comment]
wth lol, it downloaded the subtitles but not the mp4, it did however create a empty mp4 file before failing.

**Comment by majorcyto** [comment]
I also tried youtube-dl which claims to be able to pull from crunchyroll as well.. I tried it on Linux, and Windows and there's times out also when trying to pull the video stream... I submitted a bug report for them to but it was closed as a duplicate, someone else reported that error for crunchyroll 21 days ago but they haven't looked at it yet i guess.

I wonder what's making it time out. :[

**Comment by majorcyto** [comment]
Also if you like, i can give you login into to a 14.04 vps i just put up for testing, ill just reload it afterwards anyways so i don't mind letting you use it to test.

**Comment by Deathspike** [comment]
Wait, what? You had the same error on Windows 8.1? Did you install rtmpdump on Windows or did you make use of the preconfigured version that is deployed alongside crunchyroll.js (I can't recall whether I override or not)? Maybe there is a region-bound thing going on... I'm from Europe, specifically, the Netherlands. If you don't mind me asking, where are you from? And yes, by all means, please e-mail me a SSH login to test with! I'd really appreciate it.

**Comment by majorcyto** [comment]
I tried the one that came bundled, and i tried doing a custom installed version as well both failed on windows and linux! =[ I am in Texas, USA several of my servers are all in Dallas, Texas... I heard something about the connections were changed so now America and Europe have different things they connect to, but i can't be certain i think i saw that in a youtube-dl thread.

I'll e-mail it to the e-mail on your github profile.

**Comment by majorcyto** [comment]
I e-mailed the information.

**Comment by majorcyto** [comment]
Did you get it?

**Comment by atommarvel** [comment]
I'm getting the same issues on OSX:
```
WARNING: HandShake: Type mismatch: client sent 6, server answered 9
```

**Comment by evansims** [comment]
There does appear to be some sort of compatibility difference between the America and European servers. I live in Illinois and was getting the same error when I came across this thread, so I decided to try my VPN's London relay and boom, no more error.

**Comment by dggomes** [comment]
Hi, I'm having the same issue. I've checked rtmpdump version and big-integer and both are the right version.

gblonssf0800:crunchy DG$ crunchyroll -u USER -p PASS http://www.crunchyroll.com/erased/
Fetching ERASED 01x01 [CrunchyRoll]
Error: Command failed: /bin/sh -c rtmpdump -r "rtmpe://c18fs.fplive.net/c18?nvb=20160221210310&nva=20160222010410&token=0f6a3ee9900f6551f0f0a" -y "mp4:s/ve2097765/video.mp4" -W "http://www.crunchyroll.com/swf/StandardVideoPlayer.swf" -o "/Volumes/Data/Users/DG/ERASED/ERASED 01x01 [CrunchyRoll].mp4"
RTMPDump 2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: HandShake: Type mismatch: client sent 6, server answered 9
INFO: Connected...
ERROR: rtmp server sent error
ERROR: rtmp server requested close

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:471:12)

Other issue that I'm getting is that for some links and series nothing happens, see below:
gblonssf0800:crunchy DG$ crunchyroll -u USER -p PASS http://www.crunchyroll.com/erased/episode-1-flashing-before-my-eyes-691793
gblonssf0800:crunchy DG$ 

Many thanks!
